### ISSUE TITLE
Gogs Failing to start using OSE 3.2 CDK

### ISSUE THREAD

**Issue by sully6768** [alezzandro/openshift-gogs-template#1]
Hi Alessandro,

I tried running through your example.  Is there a limitation or alternative plan when using the Openshift CDK (3.2)?  I am able to get everything installed but it won't scale the instances:

Logs: 
es-mbp:rhel-ose scottes$ oc logs -f gogs-standalone-1-deploy
I0802 17:15:25.187236       1 deployer.go:196] Deploying gogs/gogs-standalone-1 for the first time (replicas: 1)
I0802 17:15:25.189957       1 recreate.go:105] Scaling gogs/gogs-standalone-1 to 1 before performing acceptance check
F0802 17:17:26.223412       1 deployer.go:65] couldn't scale gogs/gogs-standalone-1 to 1: timed out waiting for the condition

This is the same output for either the standalone or the mysql config.

I followed the steps you have defined including vagrant ssh to enter the locally running VM to allow me to run the oadm command for the scc privileges.

Hopefully this is a simple fix or I am just missing something. :)

Cheers,
SES

**Comment by sully6768** [comment]
Additional update:

Found the following in the events:

Error creating: Pod "gogs-standalone-1-" is forbidden: unable to validate against any security context constraint: [provider anyuid: .spec.containers[0].securityContext.privileged: invalid value 'true', Details: Privileged containers are not allowed provider restricted: .spec.containers[0].securityContext.privileged: invalid value 'true', Details: Privileged containers are not allowed]

**Comment by alezzandro** [comment]
Hi Scott,

I've just found the issue!

The problem was on the project name in the "oadm policy add-scc-to-user privileged system:serviceaccount:gogs-standalone:gogs" command.
I reported a wrong project name in the command: the project I've created in the example was named "gogs" but I suggest you running the command using project name "gogs-standalone".

This wrong permission left the serviceaccount gogs without the needed rights causing the errors you found.

(I've just updated the README.md in the frontpage)

Thanks a lot for reporting it back,

Let me know if you have any other issue!

Regards.
